name: workflow-example

on:
  push:
    branches:
      - main
    tags:
      -v*
      
jobs: 
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
    - uses: actions/checkout@v2
      
      
    - name: add commit
      run
