apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hosts
spec:
  rules:
  - host: koval.xyz
    http:
      paths:
        - backend:
          serviceName: main
          servicePort: 80

 