apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsecrypt-prod

  name: ingress-test
  namespace: default

spec:
  rules:
  - host: www.koval92.xyz
    http:
      paths:
        - backend:
            serviceName: main
            servicePort: 80
          path: /
  tls:
    - hosts:
      - www.koval92.xyz
      secretName: koval92-test 

 