apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
  rules:
  - host: koval92.xyz
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}
          servicePort: 80
