name: CI to Docker Hub
on:
  push:
    branches:
      - main 
    tags:
      - 'v*.*.*'
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v3
        with:
          image: docker-hub-repo/image-name
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/test:33

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
