name: CI to Docker Hub
on:
  push:
    branches:
      - main 
    tags:
      - 'v*.*.*'
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          context: ./docker
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/test:33

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
